### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by Nhahan** [s2cocos2/myblog#1]
이슈를 남겨주시지 않아 많이들 놓치시는 부분만 언급하고 갈게요.
다음부터는 이슈를 남겨주시지 않으면 따로 리뷰드리지 않습니다.
물론 없으시다면 괜찮습니다!

---

`!post.getPassword().equals(passwordDto.getPassword()` 이런 식의 비교는 null-safe하지 못하답니다. 왜냐하면 getPassword가 null일 경우 null.equals(~~)가 되어버려서 널포인터익셉션을 발생시킵니다. 물론 password가 없을리는 없어! 라고 생각하실 수 있겠지만 이런 부분은 언제 어디서 어떤 버그가 터질지 모르기에 항상 단단하게 코드를 null-safe하게 짜는 습관을 들이셔야합니다. 자바가 그렇게 생겨먹어서 어쩔 수 없는 부분이에요.

1. `post.getPassword() != null && !post.getPassword().equals(postRequestDto.getPassword())` 이렇게 null 체크를 한 번 하시고 가시거나,
2. `StringUtils.equals(post.getPassword(), postRequestDto.getPassword())` 이렇게 StringUtils라는 걸 이용해서 null-safe하게 비교하는 법도 있습니다. 보통 후자를 많이 쓰게 됩니다.

**Comment by s2cocos2** [comment]
넵 감사합니다~!반영하여 수정하도록 하였습니다!!
