### ISSUE TITLE
코드 리뷰

### ISSUE THREAD

**Issue by soon91** [s2cocos2/myblog#2]
MyblogService.java에서 비밀번호 확인 부분을 findMyblog 메서드에 포함되게 작성하셨는데

글 조회 기능을 수행 할 때 불필요한 비밀번호 확인 동작도 같이 수행이 됩니다. 

비밀번호 확인 메서드를 따로 만드시는게 나을 것 같습니다.

**Comment by s2cocos2** [comment]
문제 상황 파악하였습니다. 메서드 따로 만들어 수정하였습니다.
